uc-cdis/covid19-tools

etl_tools/johns_hopkins_etl.py
=> fix comment indent

etl_tools/johns_hopkins_etl.py
- switch to querying peregrine `summary_location` and `summary_report` separately instead of together to avoid time out. It still takes a long time and we will probably have to improve it soon when we have a little bit more data and it starts timing out again
- add US county data
- add FIPS codes for US counties
=> ETL JHU counties

seir-forecast/seir-forecast.ipynb
=> change fraction to count

covid19-etl/main.py
=> fix: domain

README.md, covid19-etl/etl/idph.py, covid19-etl/etl/idph_zipcode.py
- Parsing historical data for IDPH
=> Historical data for IDPH

Dockerfile
- fix relative path with using workdir
=> fix: add workdir for relative paths

covid19-etl/etl/idph.py
- Quick fix for IDPH data removed "negative" from JSON data
=> fix: IDPH removed "negative" field

covid19-etl/etl/ctp.py
- CTP two new fields: `dataQualityGrade` and `lastUpdateEt`
=> fix: CTP added new fields

.github/workflows/wool.yml, Dockerfile, covid19-etl/etl/ctp.py, covid19-etl/etl/ds4c.py, covid19-etl/etl/dsci.py, covid19-etl/etl/idph.py, covid19-etl/etl/idph_zipcode.py, covid19-etl/etl/jhu_to_s3.py
- ETL JHU time series data to S3
- Run black and add Wool workflow
=> feat(s3-timeseries): ETL JHU time series data to S3

covid19-etl/etl/dsci.py
=> fix DSCI class name

covid19-etl/helper/metadata_helper.py
- ETL: less verbose submission print
=> COVID19 ETL less verbose print

covid19-etl/etl/idph.py, covid19-etl/etl/idph_zipcode.py, covid19-etl/helper/metadata_helper.py
- fix IDPH ETL list index out of range error
=> fix IDPH ETL list index out of range error

covid19-etl/helper/metadata_helper.py
- JHU ETL: add retries on peregrine timeout
=> add retries on peregrine timeout

covid19-etl/etl/jhu.py, covid19-etl/helper/metadata_helper.py, covid19-etl/misc/idph_resubmit.py
Jira Ticket: COV-277/COV-279
- Add "idph_resubmit" script
- Remove "order_by" param in JHU peregrine to avoid timeouts
=> add idph_resubmit script + no peregrine order_by

README.md, covid19-etl/etl/dsfsi.py
Jira Ticket: [COV-172](https://occ-data.atlassian.net/browse/COV-172)
* Add ETL for DSFSI dataset
=> Add DSFSI ETL

covid19-etl/etl/ccmap.py
* ETL will grab the latest update (commit) datetime for CCMap files to have versioning of the data, in case it will change in the future
* Add normalization for state abbreviations to long names
=> feat: CCMap will grab the latest update (commit) datetime from Github

covid19-etl/etl/idph_zipcode.py
* Added ETL part for demographic variables for new DD
=> Adding new variables from IDPH-zipcode datasets

README.md, covid19-etl/etl/idph_facility.py
Jira Ticket: [COV-273](https://occ-data.atlassian.net/browse/COV-273)
* Add the ETL for IDPH Facility data
* Add crontab entry:
```
0  50   *   *   *    (if [ -f $HOME/cloud-automation/files/scripts/covid19-etl-job.sh ]; then JOB_NAME=idph_facility bash $HOME/cloud-automation/files/scripts/covid19-etl-job.sh; else echo "no codiv19-etl-job.sh"; fi) > $HOME/covid19-etl-$JOB_NAME-cronjob.log 2>&1
```
=> feat: ETL for IDPH Facility data

seir-forecast/generate_plots.py, seir-forecast/run_seir_forecast.sh
* Top10 scripts for homepage plots
=> feat: top10 script

seir-forecast/Dockerfile
* Add missing file to `nb-etl` Dockerfile
=> fix: add missing script to Dockerfile

covid19-etl/etl/ctp.py
* Covid Tracking Project have new fields available and updates
=> Fix for new CTP fields

covid19-etl/etl/jhu_to_s3.py
Jira Ticket: COV-364
- JHU to S3: replace value by '<5' for values <5
=> JHU to S3: replace value by '<5' for values <5

covid19-notebooks/readme.md
Jira Ticket: [COV-134](https://occ-data.atlassian.net/browse/COV-134)
add proxy for pip install
update readme
=> add pip install proxy in CTP notebook

covid19-notebooks/welcome.html
Updating the CSS for the Header and also change of content in the body
=> update of CSS and content change

covid19-etl/etl/idph_hospital.py
Jira Ticket: [COV-345](https://occ-data.atlassian.net/browse/COV-345)
* Add ETL for IDPH Hospital dataset
=> feat: IDPH Hospital ETL

covid19-notebooks/Dockerfile, covid19-notebooks/nb-etl-run.sh
Reverts uc-cdis/covid19-tools#79
=> Revert "Bullseye image"

covid19-etl/etl/jhu_country_codes.py
- Fix mistake preventing jhu_country_codes ETL to run in QA
=> Fix mistake preventing jhu_country_codes ETL to run in QA

README.md, covid19-etl/etl/chi_nbhd.py
Jira Ticket: [COV-237](https://occ-data.atlassian.net/browse/COV-237)
* Add ETL for Chicago Neighborhoods dataset
=> feat: Chicago Neighborhoods ETL

covid19-etl/etl/idph_facility.py
* Fixes IDPH Facility ETL: some of the facilities simultaneously have both "open" and "closed" statuses. This fixes it, this PR also requires extra `status` field in `summary_location`.
=> fix: handle facilities with simultaneous "open" and "close" statuses

README.md, covid19-etl/etl/coxray.py, covid19-etl/etl/coxray_file.py, covid19-etl/helper/file_helper.py
Jira Ticket: [COV-220](https://occ-data.atlassian.net/browse/COV-220)
* Add COXRAY ETL
* Improved, more readable README 🎉
=> Add COXRAY ETL

covid19-etl/etl/owid.py
=> Update ETL mapping of cumulative total to testing

covid19-etl/etl/coxray_file.py
* Small fix for unaccounted return variable from function
* Improve logging
=> fix: coxray etl issue with missing return values

covid19-notebooks/nb-etl-run.sh
- remove '--delete' flag from s3 sync in nb-etl so pod doesn't error
=> don't pass --delete in s3 sync

covid19-etl/etl/idph_hospital.py
Jira Ticket: [COV-401](https://occ-data.atlassian.net/browse/COV-401)
* Region in IDPH-Hospital now doesn't have number in the start of the string
=> feat: region name without prefix in idph-hospital

covid19-notebooks/extended-seir/extended-seir.ipynb
- remove broken link to reference in extended-seir notebook
=> remove troublesome link to reference

README.md, covid19-etl/etl/idph_zipcode.py, covid19-etl/etl/jhu_to_s3.py, covid19-etl/etl/ssr.py, covid19-etl/helper/metadata_helper.py, ssr.sh
=> Add SSR ETL

README.md, covid19-etl/etl/coxray.py, covid19-etl/etl/ctp.py, covid19-etl/etl/idph_facility.py, covid19-etl/etl/owid.py
* Update COXRAY to latest DD changes
* Fix IDPH-Facility handling of duplicate facilities (the facility with same name & status, only confirmed/deaths is different, because there is no other anchors, like offset or time, both confirmed & deaths will be updated to maximum values of available)
* CTP ETL now properly handling new value of `NaN` for numbers
* Small fix for OWID ETL to ignore two new variables `Short-term positive rate`, `Short-term tests per case`
* Update Readme 🎉 🌮
=> Fix for multiple ETL's

covid19-etl/etl/npi_pro.py
* Fixes NPI-PRO ETL with correct variable names from latest DD changes
=> feat: update NPI-PRO ETL

covid19-etl/etl/coxray.py
* COXRAY now links `imaging_file` to `follow_up`, per Yilin request
=> feat: COXRAY ETL to include image links to follow_up

covid19-etl/etl/ctp.py, covid19-etl/etl/npi_pro.py
* No changes needed, but the release will help with [COV-430](https://occ-data.atlassian.net/browse/COV-430)
* Placeholder for new variables, will be populated later [COV-428](https://occ-data.atlassian.net/browse/COV-428)
* New URL for CTP [COV-429](https://occ-data.atlassian.net/browse/COV-429)
* Includes NPI-PRO changes
=> Fix NPI-PRO and CTP ETL's

covid19-etl/etl/chi_nbhd.py
Jira Ticket: [COV-432](https://occ-data.atlassian.net/browse/COV-432)
* CHI-NBHD ETL was failing because of new JSON field names, this fixes yet (easy one)
=> fix: CHI-NBHD new JSON field names

covid19-etl/helper/metadata_helper.py
add retry logic for sheepdog submission
=> feat(retry): add retry logic

covid19-etl/helper/metadata_helper.py
=> feat(progress): add progress info

README.md, covid19-etl/etl/chestxray8.py
Jira Ticket: [COV-453](https://occ-data.atlassian.net/browse/COV-453)
* Add local-only ETL for CHESTX-RAY8 dataset
=> feat: add ETL for CHESTX-RAY8 dataset

.pre-commit-config.yaml, covid19-etl/etl/ssr.py, ssr.sh
- SSR ETL: Do not allow values < 5
- SSR ETL: exit script if fail to submit a file
=> SSR ETL: Do not allow values < 5

covid19-etl/etl/ctp.py
Fix the empty row of the race data
=> fix(emtpy_row): fix empty row

README.md, covid19-etl/etl/ctp.py
The CTP data file has a new column that results in breaking the code. This patch is created to make sure any future format changes such as: the column order, adding a new column won't break the code anymore.
- Fix CTP data file format
=> fix(ctp): fix ctp

covid19-etl/etl/vac_tracker.py
Add new enum value for `developmentStage`
=> fix(developmentStage): add more enum values

covid19-etl/etl/chestxray8.py
* `clinical_notes` in `imaging_file` will now contain the name of the folder - basically the category to which the file is related
=> fix: add "clinical_notes" to "imaging_file" node with the type of file

covid19-etl/helper/file_helper.py
* Adds header to PUT requests to indexd on updating indexd records
=> fix: pass header to PUT requests to indexd

covid19-etl/etl/jhu.py
- JHU ETL: fix failure when encountering an empty row in the input data
=> JHU: fix for empty row

covid19-etl/etl/jhu.py
=> JHU: fix empty row

Dockerfile
Fix issues building the image caused by the max pull rate limit
- Change base image to our hosted base image
=> Change base image to our hosted base image

covid19-etl/etl/jhu_to_s3.py
Jira Ticket: COV-559
- Fix occasional JHU_TO_S3 ETL failures because of missing data
=> JHU-to-S3: KeyError proof

covid19-etl/etl/ssr.py
- SSR ETL: Replace <5 values by null
=> SSR ETL: Replace <5 values by null

covid19-notebooks/bayes-by-county/r/plot-trend.r
- improve readability of bayes simulation visualizations
=> every other week for date labels

covid19-notebooks/X-ray/DarkCovidNet_binary_classes.ipynb
Modify text of DarkNet Binary Jupyter notebook.
=> Fix(Notebook): Modify text of DarkNet notebook

README.md, covid19-etl/etl/ctp.py
Jira Ticket: COV-562
- Fix CTP ETL N/A handling, update to new URL, improve error handling
=> Fix CTP URL and N/A handling

covid19-etl/etl/ncbi_file.py
The code needs to close open file when it processes the last mall file
=> fix(file): close the file

covid19-etl/etl/jhu.py, covid19-etl/utils/metadata_helper.py
Jira Ticket: COV-583, COV-585
- JHU ETL: only keep the data corresponding to the latest date
=> JHU: only keep last date

covid19-notebooks/welcome.html
Jira Ticket: [COV-578](https://ctds-planx.atlassian.net/browse/COV-578)
update the Covid-19 commons Workspace Jupyter notebooks welcome page info and formatting
=> (COV-578):style/welcome-page: update welcome page info and formatting

covid19-etl/etl/jhu.py
- JHU ETL: remove timezone from dates in submissions
=> fix JHU ETL dates

covid19-notebooks/welcome.html
Jira Ticket: [COV-578](https://ctds-planx.atlassian.net/browse/COV-578)
fix font size so title fits on one line in firefox
=> (COV-578):style/welcome-page: fix font size so title fits on one line in firefox

covid19-notebooks/X-ray/peregrine.py
X-Ray notebook: more error handling
=> xray notebook: more error handling

covid19-notebooks/Dockerfile, covid19-notebooks/run-with-slack.sh
Jira Ticket: [COV-379](https://ctds-planx.atlassian.net/browse/COV-379)
Add slack webhook to nb-etl job. Tested locally on my machine with fake exit codes from the main bash scripts.
=> Add ability to post results of job to slack

covid19-etl/etl/ctp.py, covid19-etl/etl/ncbi_file.py
Jira Ticket: [COV-802](https://occ-data.atlassian.net/browse/COV-802)
=> fix(number): fix number format

covid19-notebooks/Dockerfile, covid19-notebooks/covid19-notebook-etl-Dockerfile, covid19-notebooks/covid19-notebook-etl-requirements.txt, covid19-notebooks/covid19-notebook-etl-run-with-slack.sh, covid19-notebooks/covid19-notebook-etl-run.sh, covid19-notebooks/run-with-slack.sh
=> Small fixes to covid19-notebook-etl

covid19-etl/README.md
=> Add covid19-etl README

covid19-notebooks/pypfb/PFB_example.ipynb, covid19-notebooks/readme.md
Jira Ticket: https://occ-data.atlassian.net/browse/COV-757
Add python demonstration
=> show pfb in python

covid19-etl/etl/jhu_to_s3.py
Jira Ticket: [COV-805](https://occ-data.atlassian.net/browse/COV-805)
- add last updated date to jhu_geojson_latest.json for display on frontend
=> (COV-805): feat/addLastUpdatedDate: add last_updated to json

covid19-notebooks/pypfb/PFB_example.ipynb
Jira Ticket: COV-757
- PFB_example notebook: fix file name
=> PFB_example nb: fix file name

README.md, covid19-etl/etl/idph.py, covid19-etl/etl/idph_facility.py, covid19-etl/etl/idph_vaccine.py, covid19-etl/utils/metadata_helper.py
Jira Ticket: [COV-720](https://occ-data.atlassian.net/browse/COV-720)
- Ingest vaccine data to `summary_clinical` and `summary_group_demographic`.
=> feat(vaccine): add vaccine etl for covid19

covid19-etl/etl/idph_vaccine.py
=> fix(county): add county

covid19-etl/etl/jhu_to_s3.py
Jira Ticket: [COV-842](https://occ-data.atlassian.net/browse/COV-842)
- add new file to s3 with IL county COVID stats by time
=> (COV-842): feat/timeDataIL: add file with IL county time data

covid19-etl/etl/jhu_to_s3.py
- eliminate whitespace and line breaks from json files to save space
=> refactor/smallerJSON: eliminate whitespace and line breaks from json files to save space

covid19-etl-requirements.txt
=> aiohttp>=3.7.4

covid19-etl/etl/idph_vaccine.py
Jira Ticket: [COV-934](https://occ-data.atlassian.net/browse/COV-934)
- IDPH-Vaccine ETL: correct date time format
=> fix(date): fix datetime format

covid19-etl/etl/atlas.py, covid19-etl/etl/base.py, covid19-etl/etl/bayes_model_workflow.py, covid19-etl/etl/ccmap.py, covid19-etl/etl/chi_nbhd.py, covid19-etl/etl/com_mobility.py, covid19-etl/etl/ctp.py, covid19-etl/etl/dsfsi.py, covid19-etl/etl/idph.py, covid19-etl/etl/idph_facility.py, covid19-etl/etl/idph_hospital.py, covid19-etl/etl/idph_vaccine.py, covid19-etl/etl/idph_zipcode.py, covid19-etl/etl/jhu.py, covid19-etl/etl/jhu_to_s3.py, covid19-etl/etl/npi_pro.py, covid19-etl/etl/owid.py, covid19-etl/etl/owid2.py, covid19-etl/etl/stoplight.py, covid19-etl/etl/vac_tracker.py
Jira Ticket: https://occ-data.atlassian.net/browse/COV-947
- IDPH_Vaccine ETL: add mapping for 'race' value 'Middle Eastern or North Africa' + add progress logging
- Add retries to GET requests for all ETLs
=> Add GET requests retries + fix IDPH_Vaccine ETL 'race'

covid19-etl/etl/idph_facility.py, covid19-etl/etl/idph_vaccine.py, covid19-etl/utils/format_helper.py
Jira Ticket: [COV-783](https://occ-data.atlassian.net/browse/COV-783)
- We can now get IDPH-facility data over a date range from the source.
- IDPH-facility source url which was deprecated since 11/06/2020 is updated with a new url
=> Update IDPH-Facility ETL

generative_bayes_model/Dockerfile, generative_bayes_model/gbm-run-with-slack.sh, generative_bayes_model/gbm-run.sh, generative_bayes_model/pymc3_generative_model.py
* Added new commands to the Dockerfile so as to run the python script
=> Feat Model -- Added new facets to Dockerfile

covid19-notebooks/readme.md
Jira Ticket: [COV-1077](https://occ-data.atlassian.net/browse/COV-1077)
update readme to include all 16 notebooks we have currently.
=> missing notebook added to readme

generative_bayes_model/pymc3_generative_model.py
=> replace url

covid19-etl/etl/idph_hospital_utilization.py
Jira Ticket: [COV-1079](https://occ-data.atlassian.net/browse/COV-1079)
* Add more logs to understand intermittent duplicate submission error in `idph_hospitalization_etl`
=> (COV-1079): Prevent duplicate record submission in `idph_hospitalization_etl`

generative_bayes_model/gbm-run.sh
* Check if the python script is successful	before performing the file upload to S3
=> Fix false positive success result

generative_bayes_model/gbm-run.sh, generative_bayes_model/pymc3_generative_model.py
Jira Ticket: [COV-1081](https://occ-data.atlassian.net/browse/COV-1081)
The data source for the bayes model scripts didn't update their data for 7 days due to the holidays, however, the scripts didn't capture that. The "average missing data points" function needs a fix.
=> update averaging funcion

covid19-etl/misc/harmonization_scripts/SIU_Rscript.R
=> Update to SIU script

covid19-notebooks/IL_tab_charts.ipynb, covid19-notebooks/google_mobility.ipynb
To solve the problem reported here https://cdis.slack.com/archives/CV4HHPB9Q/p1654106549424949
=> change table name for bigquery-public-data.covid19_google_mobility data

.github/workflows/build_covid19-notebook-etl.yml, .pre-commit-config.yaml, covid19-etl/etl/vac_tracker.py
-  Update vac tracker ETL to the new dataset URL
=>  Update vac tracker to new dataset URL

covid19-etl/etl/idph_vaccine_to_s3.py
Jira Ticket: [PXP-10882](https://ctds-planx.atlassian.net/browse/PXP-10882)
- Fix IDPH-vaccine-to-S3 ETL to handle null values
[PXP-10882]: https://ctds-planx.atlassian.net/browse/PXP-10882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PXP-10882 IDPH-to-S3 etl: handle latest date potentially None value
